### PR TITLE
Fix demo deck fallback when deck.md doesn't exist

### LINKED ISSUE #4: Demo deck fallback fails when deck.md doesn't exist
# Description
When running quarkus-reveal with the default deck file (deck.md) that doesn't exist, the application should fall back to the demo deck but instead throws an IOException.
## Steps to Reproduce

Run `quarkus-reveal -t quarkus` in a directory without a deck.md file
The application crashes with the following error:
```
java.io.IOException: File not found: deck.md
        at ia3andy.QuarkusReveal$FileCache.read(QuarkusReveal.java:228)
        at ia3andy.QuarkusReveal.call(QuarkusReveal.java:89)
        at ia3andy.QuarkusReveal.call(QuarkusReveal.java:55)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1953)
        at picocli.CommandLine.access$1300(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
        at picocli.CommandLine.execute(CommandLine.java:2078)
        at ia3andy.QuarkusReveal.main(QuarkusReveal.java:73)

```
## Expected Behavior

The application should detect that deck.md doesn't exist, set resolvedDeck = "DEMO", and use the built-in demo deck content.

## Actual Behavior
The application attempts to read the non-existent deck.md file and crashes with an IOException.
## Root Cause
In the `call()` method, the code correctly detects when deck.md doesn't exist and sets resolvedDeck = "DEMO", but then immediately tries to read from the original deckPath regardless of whether it was resolved to the demo deck

## Proposed Solution
Wrap the file reading and front matter parsing in a conditional check to only execute when resolvedDeck is not "DEMO".

### PR DESCRIPTION
**Pull request by ayagmar**
- Prevents IOException when falling back to demo content

image

- Fixes : #4

### CODE REVIEW

File: QuarkusReveal.java [hunk 1]
```diff
@@ -86,6 +86,8 @@ public Integer call() throws Exception { // your business logic goes here...
                 throw new IOException("Deck file not found: " + deck);
             }
         }
+     // Only read and parse front matter if we have an actual file (not DEMO)
+        if (!resolvedDeck.equals("DEMO")) {
```
Comment (zakkak) [inline QuarkusReveal.java:90]: It looks like there is a formatting issue. Spaces vs tabs?

Comment (ayagmar) [reply QuarkusReveal.java:90]: should be better now

**Review by zakkak — CHANGES_REQUESTED** [review]
There are still styling issues, the body of the if statement should get indented, along with the closing bracket.
